export { default as HeroLine } from '@/public/svg/hero-line.svg'
export { default as BlueCircle } from '@/public/svg/blur-circle.svg'
export { default as PointIcon } from '@/public/svg/point-icon.svg'
export { default as WorkflowLine } from '@/public/svg/workflow-line.svg'
export { default as Star } from '@/public/svg/star.svg'
export { default as Logo } from '@/public/svg/logo.svg'
export { default as FounderLine } from '@/public/svg/founder-line.svg'
export { default as DoubleQuotes } from '@/public/svg/double-quotes.svg'

export { default as Facebook } from '@/public/svg/facebook.svg'
export { default as Instagram } from '@/public/svg/instagram.svg'
export { default as LinkedIn } from '@/public/svg/linkedIn.svg'


export { default as CompanyLogo1 } from '@/public/svg/companylogo/01.svg'
export { default as CompanyLogo2 } from '@/public/svg/companylogo/02.svg'
export { default as CompanyLogo3 } from '@/public/svg/companylogo/03.svg'
export { default as CompanyLogo4 } from '@/public/svg/companylogo/04.svg'
export { default as CompanyLogo5 } from '@/public/svg/companylogo/05.svg'
export { default as CompanyLogo6 } from '@/public/svg/companylogo/06.svg'