export { default as HomePage } from './HomePage'
export { default as AboutPage } from './AboutPage'
export { default as CaseStudiesPage } from './CaseStudiesPage'
export { default as SingleCaseStudyPage } from './SingleCaseStudyPage'
export { default as ContactUsPage } from './ContactUsPage'